import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SearchBar from "@/components/SearchBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="bg-slate-800 min-h-dvh flex flex-col">
          <SearchBar />
          <div className="flex grow place-content-center">{children}</div>
          <footer className="flex w-full place-content-center bg-black">
            <div className="w-fit">Footer Stuff</div>
          </footer>
        </main>
      </body>
    </html>
  );
}
